let tags = [
  "16th century",
  "17th century",
  "18th century",
  "19th century",
  "20th Century",
  "Active Filtration",
  "Agnes Denes",
  "AI",
  "air",
  "Alchemy",
  "Algae",
  "AMID (Cero9)",
  "Amy Balkin",
  "An Te Liu",
  "Andrew Lewthwaite",
  "Ant-farm",
  "Antoine Lavoisier",
  "Archeology",
  "Architecture",
  "Arhitecture",
  "Aristotle",
  "Assemblage",
  "Astroballon",
  "Bacteria",
  "Benjamin Gaulon",
  "Big Leaks",
  "BIO",
  "Bio-Integrated Design",
  "biomaterials",
  "Blur Building",
  "Bodies of Planned obsolescence",
  "Breathing",
  "Bruno Latour",
  "Bubbles",
  "Building Envelope",
  "Building material",
  "Building system",
  "C-Lab",
  "camouflage",
  "capture",
  "CAST",
  "Catastrophies Domestiques - N2",
  "chemistry",
  "chimney",
  "cinema",
  "Cita Group",
  "Citation",
  "citizen action",
  "Clouds",
  "CO2",
  "Coal",
  "color",
  "Compost",
  "Computer Industry",
  "Concrete",
  "contagion",
  "Contagious Architecture",
  "contemporary art",
  "Coop Himmelblau",
  "cultural anthropology",
  "Dan Peterman",
  "Dark",
  "Data",
  "David Gissen",
  "decay",
  "delete",
  "Dennis Oppenheim",
  "Design",
  "Digital",
  "Digital Culture Research Center",
  "digital fabrication techniques",
  "Diller & Scofidio",
  "Dirt",
  "DIY",
  "domestic",
  "Dominique Sirois",
  "Drawing",
  "Dust",
  "Dustin Tobias",
  "Eco-Scale",
  "Ecological Thought",
  "Ecology",
  "Ecoscale",
  "Elda Danese",
  "Electronics",
  "Electrostatic-Skin",
  "Ensadlab",
  "Ephemeral",
  "Eszter Ozsvald",
  "etching",
  "Etymology",
  "Exhaust",
  "Exhibition",
  "Extraction",
  "Eyal Weizman",
  "Field Work",
  "Filtration",
  "flood",
  "Forensic Architecture",
  "Free-Soil",
  "Fujiko Nakaya",
  "Future Cities Lab",
  "Future Farmers",
  "Gabris Jennifer",
  "gas",
  "Geology",
  "Georges Bataille",
  "geotextiles",
  "Gilberto Esparza",
  "Glasshouse",
  "globalization",
  "Goethe",
  "Greg Lynn",
  "Gregory Chatonski",
  "health",
  "HeHe",
  "Histories and Practices of Ecology",
  "HISTORY",
  "history of science",
  "Hubert Damisch",
  "HVAC",
  "Hydrological Infrastructures",
  "industrialization",
  "Industry-Partnership",
  "Inflatable Structures",
  "Infrastructure",
  "Innovative Materials",
  "Innovative Technologies",
  "Installation",
  "installation concepts",
  "Interactive",
  "Interdisplinery",
  "Intervention",
  "Jacob Remin",
  "Jean Hauser",
  "Jean-Marc Chomaz",
  "Jean-Pierre Aubé",
  "Jeffery Shaw",
  "Jeffrey Inaba",
  "John Ruskin",
  "Jorge Otero-Pailos",
  "Junniper Harrower",
  "Jussi Parikka",
  "Kärt Ojavee",
  "Kristiina Ljokkoi",
  "labels",
  "landscape",
  "Lars Spuybroek",
  "Larvae",
  "later",
  "laura Kurgan",
  "learning",
  "Light",
  "Links",
  "literature",
  "Luciana Parisi",
  "Machine",
  "Main-Question",
  "Manuel Kretzer",
  "Mapping",
  "Marjetica Potrc and Ooze",
  "Martin Howse",
  "Martina Decker",
  "Mary Douglas",
  "Material",
  "material science.",
  "material signifier",
  "Media-Archaeology",
  "Meeting-Summary",
  "Mel Chin",
  "membrane",
  "Mette Ramsgard Thomsen",
  "Miasma",
  "Michael Wihart",
  "Microclimates",
  "Mierle Laderman Ukules",
  "Minerals",
  "modern art",
  "Moisture",
  "molds",
  "Mushrooms",
  "Nannette Jackowski",
  "Nanoscale",
  "Nasa",
  "national institute experimental arts",
  "Natural Vitalism",
  "networks",
  "Nicola Sabbatini",
  "NL Architects",
  "Odor",
  "Olfactory",
  "Omar Khan",
  "orrizontale",
  "parametric design",
  "Participatory approach",
  "Passive Filtration",
  "Paul Rudolph",
  "Paul Vanouse",
  "Pedagogy",
  "performance",
  "performative materials",
  "Phil Ayres",
  "Philippe Rahm",
  "Physarum",
  "Pierre Bélanger",
  "Pierre Huyghe",
  "Plants",
  "Plastic",
  "pollution",
  "post-industrial",
  "preservation",
  "private",
  "projection",
  "Protection",
  "public",
  "puddles",
  "R&Sie(n)",
  "Recycling",
  "Reflective Interactions",
  "Remediation",
  "remote space",
  "remote times",
  "Research Lab",
  "RESEARCH-CREATION",
  "Residue",
  "Residues",
  "responsive architecture",
  "Ricardo de Ostos",
  "Robotic",
  "Roland Fréart de Chambray",
  "Ruairi Glynn’s",
  "Ruins",
  "Samer Afifi",
  "Sampling as Methodology",
  "Sand",
  "Scientists",
  "sculpture",
  "Sean Lally",
  "Sedimentation",
  "Senseable City Labs",
  "shade",
  "Shaun Murray",
  "Simon Starling",
  "Sink",
  "Smell",
  "smoke",
  "SmoutAllen",
  "Sneha Patel",
  "Social-relation",
  "Soft",
  "Soft Matters",
  "Soft temporalities",
  "soft-infrastructures",
  "soft-robotics",
  "soft-speculation",
  "Soil",
  "Solar energy",
  "sound",
  "speculative design",
  "Stagnancy",
  "strata",
  "Subnature",
  "summary",
  "surface",
  "Sven Anderson",
  "Symbiosis",
  "technology",
  "Teresa Margoles",
  "textile",
  "The Architecture of Soft Machines",
  "the cave",
  "The Ethics of Dust Series",
  "THEORY",
  "Thermal",
  "Thom Faulders",
  "Threat",
  "Transdisciplinary",
  "transhumanism",
  "UCL",
  "uncube",
  "urban",
  "Utopia",
  "Vera Thaens",
  "Visualizing Smoke",
  "Vlan Paysage",
  "Waste",
  "water",
  "wearables",
  "weeds",
  "West 8",
  "William Burroughs",
  "Yoha Art",
  "Zbigniew Oksiuta"
]
